# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: cd
on:
  workflow_dispatch:
  check_run:
    types:
      - completed

jobs:
  maven-cd:
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@791f6a10b7e9084eb9d6742293df4a562a801a8d # v1.8.2
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
