# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: cd
on:
  workflow_dispatch:
  check_run:
    types:
      - completed

jobs:
  maven-cd:
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@e363d9f9c7b5a757ad75a3a40663fd1158ebc811 # v1.8.1
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
